services:
  - type: web
    name: financial-tracker-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false
